/* ============================================================
   RUSTLE UP — a fully local recipe manager, meal planner and
   shopping list. No backend, no API calls, no accounts.
   Everything lives in IndexedDB on this device. Use Export/Import
   (Settings tab) to move your library between devices.

   Data model:
   - recipes: the recipe library (IndexedDB object store).
   - meta.mealPlan: array of recipe ids you're cooking this period.
   - meta.shopItems: the shopping list -- generated by merging
     ingredients from meal-plan recipes (by parsed quantity +
     ingredient-catalog matching), plus any manual items. Once you
     edit an item's text by hand it's "detached" and won't be
     touched by future merges.
   - meta.ingredientCatalog: your canonical ingredient list, used
     to merge differently-worded ingredients together and to flag
     staples.
   ============================================================ */

const DB_NAME = "recipe-box";
const DB_VERSION = 1;
const STORE = "recipes";
let db;
let currentTab = "recipes";
let currentSearch = "";
let currentTagFilter = "";
let pendingImport = null; // recipes parsed but awaiting serves confirmation
let recipesFlash = ""; // one-shot status message shown on the Recipes tab
let shopFlash = null; // { message, undo: async fn | null } shown on the Shopping List tab
let showCheckedItems = false;

const CATEGORY_ORDER = ["Produce", "Meat & Fish", "Dairy & Eggs", "Bakery", "Pantry", "Frozen", "Drinks", "Other"];

const DEFAULT_INGREDIENT_CATALOG = [
  { id: "salt", name: "Salt", category: "Pantry", staple: true, aliases: ["salt"] },
  { id: "black-pepper", name: "Black pepper", category: "Pantry", staple: true, aliases: ["black pepper", "pepper"] },
  { id: "olive-oil", name: "Olive oil", category: "Pantry", staple: true, aliases: ["olive oil", "extra virgin olive oil"] },
  { id: "cooking-oil", name: "Cooking oil", category: "Pantry", staple: true, aliases: ["vegetable oil", "sesame oil", "sunflower oil"] },
  { id: "sugar", name: "Sugar", category: "Pantry", staple: true, aliases: ["sugar"] },
  { id: "flour", name: "Plain flour", category: "Pantry", staple: true, aliases: ["plain flour", "flour"] },
  { id: "vinegar", name: "Vinegar", category: "Pantry", staple: true, aliases: ["vinegar"] },
  { id: "soy-sauce", name: "Soy sauce", category: "Pantry", staple: true, aliases: ["soy sauce"] },
  { id: "stock-cube", name: "Stock cubes", category: "Pantry", staple: true, aliases: ["stock cube", "stock cubes"] },
  { id: "rice-pouch", name: "Basmati rice (pouch)", category: "Pantry", staple: false,
    aliases: ["rice sachet", "packet of rice", "wholegrain rice", "basmati rice", "wholegrain basmati rice", "cooked rice"] }
];

function genId() {
  return Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);
}

function openDB() {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = (e) => {
      const database = e.target.result;
      if (!database.objectStoreNames.contains(STORE)) {
        database.createObjectStore(STORE, { keyPath: "id" });
      }
      if (!database.objectStoreNames.contains("meta")) {
        database.createObjectStore("meta", { keyPath: "key" });
      }
    };
    req.onsuccess = (e) => resolve(e.target.result);
    req.onerror = (e) => reject(e.target.error);
  });
}

function tx(storeName, mode) {
  return db.transaction(storeName, mode).objectStore(storeName);
}

function getAllRecipes() {
  return new Promise((resolve, reject) => {
    const req = tx(STORE, "readonly").getAll();
    req.onsuccess = () => resolve(req.result || []);
    req.onerror = () => reject(req.error);
  });
}

function putRecipe(recipe) {
  return new Promise((resolve, reject) => {
    const req = tx(STORE, "readwrite").put(recipe);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

function deleteRecipe(id) {
  return new Promise((resolve, reject) => {
    const req = tx(STORE, "readwrite").delete(id);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

function getMeta(key) {
  return new Promise((resolve) => {
    const req = tx("meta", "readonly").get(key);
    req.onsuccess = () => resolve(req.result ? req.result.value : null);
    req.onerror = () => resolve(null);
  });
}

function setMeta(key, value) {
  return new Promise((resolve, reject) => {
    const req = tx("meta", "readwrite").put({ key, value });
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

function slugify(str) {
  return str.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

/* ---------- Meta-backed collections ---------- */

async function getMealPlan() { return (await getMeta("mealPlan")) || []; }
async function saveMealPlan(ids) { await setMeta("mealPlan", ids); }

async function getShopItems() { return (await getMeta("shopItems")) || []; }
async function saveShopItems(items) { await setMeta("shopItems", items); }

async function getIngredientCatalog() { return (await getMeta("ingredientCatalog")) || []; }
async function saveIngredientCatalog(cat) { await setMeta("ingredientCatalog", cat); }
async function seedCatalogIfEmpty() {
  const existing = await getIngredientCatalog();
  if (existing.length === 0) await saveIngredientCatalog(DEFAULT_INGREDIENT_CATALOG.map(e => ({ ...e })));
}

/* ---------- Ingredient quantity parsing & merging ----------
   Best-effort: cookbook ingredient lines are messy free text, so
   this only merges when it can confidently extract a quantity and
   name. Anything it can't parse just becomes its own line -- same
   safe fallback as before, but now it usually *can* merge. */

const UNIT_MAP = {
  g: "g", gram: "g", grams: "g",
  kg: "kg", kilogram: "kg", kilograms: "kg",
  ml: "ml", millilitre: "ml", millilitres: "ml", milliliter: "ml", milliliters: "ml",
  l: "l", litre: "l", litres: "l", liter: "l", liters: "l",
  cm: "cm",
  tsp: "tsp", teaspoon: "tsp", teaspoons: "tsp",
  tbsp: "tbsp", tablespoon: "tbsp", tablespoons: "tbsp",
  clove: "clove", cloves: "clove",
  head: "head", heads: "head",
  bunch: "bunch", bunches: "bunch",
  tin: "tin", tins: "tin", can: "tin", cans: "tin"
};
const WORD_UNITS = ["clove", "head", "bunch", "tin"];

function normalizeUnit(u) { return UNIT_MAP[u.toLowerCase()] || u.toLowerCase(); }

function parseQtyToken(tok) {
  const fracMap = { "½": 0.5, "¼": 0.25, "¾": 0.75, "⅓": 1 / 3, "⅔": 2 / 3 };
  if (fracMap[tok] !== undefined) return fracMap[tok];
  if (tok.indexOf("/") !== -1) {
    const parts = tok.split("/");
    const n = Number(parts[0]), d = Number(parts[1]);
    if (d) return n / d;
  }
  return parseFloat(tok);
}

function cleanIngredientName(name) {
  let n = name.trim();
  n = n.replace(/^(a|an|of)\s+/i, "");
  n = n.replace(/^(tins?|cans?|packets?|sachets?|jars?|bags?)\s+of\s+/i, "");
  return n.trim();
}

function extractParenWeight(name) {
  const m = name.match(/\((\d+(?:\.\d+)?)\s*(g|kg|ml|l)\)\s*$/i);
  if (!m) return { name, parenAmount: null, parenUnit: null };
  return { name: name.slice(0, m.index).trim(), parenAmount: parseFloat(m[1]), parenUnit: normalizeUnit(m[2]) };
}

function parseIngredient(raw) {
  const text = raw.trim();

  // "N x SIZEunit ..." e.g. "2 x 400g tins of chickpeas"
  let m = text.match(/^(\d+(?:\.\d+)?|\d+\/\d+|½|¼|¾|⅓|⅔)\s*x\s*(\d+(?:\.\d+)?)\s*(g|kg|ml|l)\b\s*(.*)$/i);
  if (m) {
    const packCount = parseQtyToken(m[1]);
    const packSize = parseFloat(m[2]);
    const unit = normalizeUnit(m[3]);
    const name = cleanIngredientName(m[4]);
    return { amount: packCount * packSize, unit, name, parenAmount: null, parenUnit: null };
  }

  // leading qty + unit, with an optional qualifier word e.g. "2 heaped tablespoons peanut butter"
  m = text.match(/^(\d+(?:\.\d+)?|\d+\/\d+|½|¼|¾|⅓|⅔)\s*(?:(?:heaped|level|rounded|scant|generous)\s+)?(g|kg|ml|l|cm|tsp|tbsp|teaspoons?|tablespoons?|cloves?|heads?|bunche?s?|tins?|cans?)\b\.?\s*(?:of\s+)?(.*)$/i);
  if (m) {
    const amount = parseQtyToken(m[1]);
    const unit = normalizeUnit(m[2]);
    const name = cleanIngredientName(m[3]);
    return { amount, unit, name, parenAmount: null, parenUnit: null };
  }

  // plain leading number, no unit, e.g. "2 onions (320g)"
  m = text.match(/^(\d+(?:\.\d+)?|\d+\/\d+|½|¼|¾|⅓|⅔)\s+(.*)$/);
  if (m) {
    const amount = parseQtyToken(m[1]);
    const extracted = extractParenWeight(cleanIngredientName(m[2]));
    return { amount, unit: null, name: extracted.name, parenAmount: extracted.parenAmount, parenUnit: extracted.parenUnit };
  }

  return { amount: null, unit: null, name: cleanIngredientName(text), parenAmount: null, parenUnit: null };
}

function formatNum(n) {
  if (n == null) return "";
  const rounded = Math.round(n * 100) / 100;
  return String(rounded);
}

function pluralizeUnit(unit, amount) {
  if (!WORD_UNITS.includes(unit)) return unit;
  if (amount === 1) return unit;
  return unit === "bunch" ? "bunches" : unit + "s";
}

function formatQuantity(amount, unit) {
  if (amount == null) return "";
  if (!unit) return formatNum(amount);
  if (["g", "kg", "ml", "l", "cm"].includes(unit)) return `${formatNum(amount)}${unit}`;
  return `${formatNum(amount)} ${pluralizeUnit(unit, amount)}`;
}

function formatItemText(item) {
  const qty = formatQuantity(item.amount, item.unit);
  let text = qty ? `${qty} ${item.name}` : item.name;
  if (item.parenAmount != null) text += ` (${formatNum(item.parenAmount)}${item.parenUnit})`;
  return text;
}

function matchCatalog(name, catalog) {
  const norm = name.toLowerCase();
  let best = null, bestLen = 0;
  catalog.forEach(entry => {
    (entry.aliases || []).forEach(alias => {
      const a = alias.toLowerCase().trim();
      if (a && norm.indexOf(a) !== -1 && a.length > bestLen) {
        best = entry;
        bestLen = a.length;
      }
    });
  });
  return best;
}

function buildMergeKey(catalogEntry, name) {
  return catalogEntry ? "cat:" + catalogEntry.id : "text:" + name.toLowerCase().trim();
}

/* ---------- Seed data: the recipes already on hand ---------- */
const SEED_RECIPES = [
  {
    id: "mothership-overnight-oats",
    title: "Mothership Overnight Oats",
    source: "Cookbook (adapted)",
    tags: ["breakfast", "batch-prep", "vegetarian"],
    servesLabel: "Makes 6 portions",
    time: "10 min + overnight soak",
    ingredients: [
      "2 ripe bananas (320g)",
      "700ml semi-skimmed milk or unsweetened fortified plant milk",
      "2 teaspoons vanilla bean paste",
      "300g porridge oats",
      "2 eating apples"
    ],
    method: [
      "Blend the peeled bananas with the milk and vanilla bean paste until smooth, then pour over the oats in a large bowl.",
      "Coarsely grate in the apples and stir well.",
      "Cover and refrigerate overnight.",
      "The next day, stir well and loosen with a splash more milk if needed. Serve as is, or top with seasonal fruit, nuts or seeds."
    ],
    notes: "Keeps in the fridge for several days. Easy to halve for one person (220g per portion).",
    dateAdded: "2026-07-11"
  },
  {
    id: "comforting-chickpea-cauliflower-soup",
    title: "Comforting Chickpea & Cauliflower Soup",
    source: "Cookbook (adapted)",
    tags: ["soup", "curry", "vegetarian", "batch-prep"],
    servesLabel: "Serves 4",
    time: "Prep 15 min, cook 25 min",
    ingredients: [
      "4cm piece of ginger",
      "4 cloves of garlic",
      "2 onions (320g)",
      "1 small handful of curry leaves",
      "1 head of cauliflower (800g)",
      "500g potatoes",
      "3 tablespoons curry paste",
      "60g coconut cream",
      "2 x 400g tins of chickpeas",
      "200g ripe mixed-colour cherry tomatoes"
    ],
    method: [
      "Finely chop the ginger, garlic and onion, and cook in a large pan with a little oil and the curry leaves over medium heat.",
      "Chop the potatoes and cauliflower into rough dice and add to the pan, cooking for around 10 minutes, stirring regularly.",
      "Stir in the coconut cream, then add the chickpeas (with their liquid) and enough boiling water to just cover. Cover and simmer.",
      "Blend roughly half the soup until smooth, then stir back through the rest for a creamier texture.",
      "Divide between bowls, top with quartered cherry tomatoes, and drizzle with olive oil if you like."
    ],
    notes: "Inspired by aloo gobi. Good with warmed flatbread.",
    dateAdded: "2026-07-11"
  },
  {
    id: "super-green-orecchiette",
    title: "Super-Green Orecchiette",
    source: "Cookbook (adapted)",
    tags: ["pasta", "vegetarian", "weeknight"],
    servesLabel: "Serves 4",
    time: "24 min",
    ingredients: [
      "80g rosemary focaccia",
      "4 cloves of garlic",
      "1 head of broccoli (320g)",
      "320g baby spinach",
      "50g Parmesan cheese",
      "1 lemon",
      "dried red chilli flakes",
      "300g dried orecchiette",
      "320g frozen peas",
      "4 tablespoons cottage cheese"
    ],
    method: [
      "Blitz the focaccia into fine crumbs and toast in a dry pan until golden; set aside.",
      "Boil the whole garlic cloves in salted water. Cut the broccoli into florets, roughly chop the stalk, and add the stalk to the water along with the spinach for the final minute.",
      "Lift out the broccoli stalk, spinach and garlic (reserve the water for the pasta) and blend with lemon juice, grated Parmesan, chilli flakes and olive oil into a smooth green sauce. Season to taste.",
      "Cook the orecchiette in the same pot of water according to packet instructions, adding the broccoli florets and peas for the final 2 minutes.",
      "Drain, reserving a mugful of pasta water, then toss the pasta with the green sauce, loosening with a little pasta water if needed.",
      "Divide between bowls, spoon over the cottage cheese, and scatter with the crispy crumbs and a pinch of chilli flakes."
    ],
    notes: "",
    dateAdded: "2026-07-11"
  },
  {
    id: "creamy-peanut-chicken",
    title: "Creamy Peanut Chicken",
    source: "Cookbook (adapted)",
    tags: ["chicken", "quick", "weeknight"],
    servesLabel: "Serves 2",
    time: "10 min",
    ingredients: [
      "2 mixed-colour peppers (320g)",
      "2 x 150g skinless chicken breasts",
      "2 cloves of garlic",
      "6cm piece of ginger",
      "2 limes",
      "1 tablespoon low-salt soy sauce",
      "2 heaped tablespoons peanut butter",
      "½ a bunch of coriander (15g)",
      "160g sugar snap peas",
      "60g dried mango"
    ],
    method: [
      "Slice the peppers into thick strips, discarding the seeds, and dry-fry in a hot pan for 2 minutes.",
      "Slice the chicken into 1cm strips, season, add to the pan with a little oil, and cook for about 4 minutes until golden, tossing regularly.",
      "Meanwhile, blend the garlic, ginger, lime juice, soy sauce, peanut butter, coriander stalks and a splash of water into a smooth sauce, and season to taste.",
      "Add the sugar snaps and dried mango to the pan, pour in the sauce, and let it bubble for 2 minutes.",
      "Plate up, scatter with coriander leaves, and serve with lime wedges and rice or noodles."
    ],
    notes: "",
    dateAdded: "2026-07-11"
  },
  {
    id: "easy-prawn-curry",
    title: "Easy Prawn Curry",
    source: "Cookbook (adapted)",
    tags: ["seafood", "curry", "quick"],
    servesLabel: "Serves 2",
    time: "10 min",
    ingredients: [
      "1 onion (160g)",
      "250g ripe cherry tomatoes",
      "1 x 50g sachet of creamed coconut",
      "1 x 400g tin of chickpeas",
      "1 bunch of coriander (30g)",
      "2 tablespoons curry paste",
      "250g frozen mango",
      "165g raw peeled king prawns",
      "1 x 250g packet of cooked wholegrain basmati rice",
      "30g Bombay mix"
    ],
    method: [
      "Finely slice the onion and dry-fry with the tomatoes for about 4 minutes.",
      "Meanwhile, blend the creamed coconut, chickpeas (with their liquid), half the coriander leaves and a splash of water into a sauce, along with half the cooked onion and tomato.",
      "Stir the curry paste and a little oil into the pan with the remaining onion and tomato, then add the mango and remaining chickpeas and toss for 2 minutes.",
      "Pour in the blended sauce, add the prawns, and simmer until just cooked through, loosening with water if needed.",
      "Cook the rice according to packet instructions and divide between plates. Stir most of the remaining coriander through the curry, spoon over the rice, and finish with crushed Bombay mix."
    ],
    notes: "",
    dateAdded: "2026-07-11"
  },
  {
    id: "chipotle-chicken-bean-soup",
    title: "Chipotle Chicken & Bean Soup",
    source: "Cookbook (adapted)",
    tags: ["soup", "chicken", "batch-prep"],
    servesLabel: "Serves 4",
    time: "Prep 20 min, cook 1 hour",
    ingredients: [
      "4 large chicken thighs, skin on, bone in",
      "320g button mushrooms",
      "2 red onions (320g)",
      "4 carrots (320g)",
      "320g celery",
      "4 teaspoons chipotle chilli paste",
      "2 x 400g tins of butter beans",
      "2 x 400g tins of plum tomatoes",
      "1 small ripe avocado (160g)",
      "1 lime"
    ],
    method: [
      "Render the skin from the chicken thighs in a large casserole pan over medium heat, then remove and reserve the skin, leaving the fat behind.",
      "Season the thighs and brown them in the pan while you trim the mushrooms and finely slice the onions, carrots and celery (reserving any celery leaves). Remove the chicken and cook the vegetables for about 10 minutes.",
      "Stir in the chipotle paste, return the chicken to the pan, add the tomatoes (breaking them up) and a kettle's worth of water. Cover and simmer for 45 minutes.",
      "Pull out the chicken and shred it, discarding the bones, then stir it back into the soup with the beans and simmer to your desired consistency.",
      "Halve, destone, peel and dice the avocado, and dress with lime juice. Serve the soup topped with the avocado, reserved celery leaves, and crumbled crispy tortilla for crunch, if you like."
    ],
    notes: "Good with warmed or roasted corn tortillas on the side.",
    dateAdded: "2026-07-11"
  },
  {
    id: "golden-chicken-peppers-rice",
    title: "Golden Chicken, Peppers & Rice",
    source: "Cookbook (adapted)",
    tags: ["chicken", "quick", "weeknight"],
    servesLabel: "Serves 2",
    time: "14 min",
    ingredients: [
      "160g kale",
      "½ a head of broccoli (160g)",
      "1 red pepper (160g)",
      "2 x 150g skinless chicken breasts",
      "1 x 250g packet of cooked wholegrain rice",
      "1 tablespoon harissa paste, plus extra to serve",
      "1 lemon",
      "30g feta cheese",
      "2 heaped tablespoons houmous"
    ],
    method: [
      "Tear the kale into a hot dry pan, discarding any tough stalks, and let it wilt and lightly char. Meanwhile cut the broccoli into small florets, slice the pepper, and cut the chicken into 1cm strips.",
      "Once the kale has wilted, tip in the rice and harissa paste, add half the lemon juice, and toss over the heat for 2 minutes until hot through. Season and divide between plates.",
      "Add a tablespoon of olive oil to the pan, then the chicken and broccoli. Season and cook for a few minutes until golden and cooked through, tossing regularly. Add the pepper partway through.",
      "Divide the chicken, peppers and broccoli over the rice, crumble over the feta, and spoon over the houmous and a little extra harissa. Serve with the remaining lemon."
    ],
    notes: "",
    dateAdded: "2026-07-11"
  },
  {
    id: "sesame-miso-shred-salad",
    title: "Sesame Miso Shred Salad",
    source: "Cookbook (adapted)",
    tags: ["salad", "side", "vegetarian", "quick"],
    servesLabel: "Serves 1",
    time: "12 min",
    ingredients: [
      "80g each of sugar snap peas, white cabbage, yellow pepper, carrot, asparagus",
      "1 fresh red chilli",
      "1 lime",
      "1 heaped teaspoon tahini",
      "1 heaped teaspoon white miso",
      "1 heaped teaspoon toasted sesame seeds",
      "2 sprigs of coriander"
    ],
    method: [
      "Trim or deseed the vegetables as needed, then finely shred them all, by hand or with a food processor attachment.",
      "Finely chop the chilli and scrunch it through the shredded veg with the lime juice, tahini, miso and a little extra virgin olive oil.",
      "Season to taste, then scatter over the sesame seeds and pick over the coriander leaves.",
      "Good as a side with wholegrain rice or noodles."
    ],
    notes: "",
    dateAdded: "2026-07-11"
  }
];

/* ---------- Rendering ---------- */

async function seedIfEmpty() {
  const existing = await getAllRecipes();
  if (existing.length === 0) {
    for (const r of SEED_RECIPES) await putRecipe(r);
  }
}

function allTags(recipes) {
  const s = new Set();
  recipes.forEach(r => (r.tags || []).forEach(t => s.add(t)));
  return Array.from(s).sort();
}

function searchRank(r, term) {
  const t = term.toLowerCase();
  if (r.title.toLowerCase().includes(t)) return 0;
  if ((r.tags || []).some(tag => tag.toLowerCase().includes(t))) return 1;
  if ((r.ingredients || []).some(i => i.toLowerCase().includes(t))) return 2;
  if ((r.source || "").toLowerCase().includes(t) || (r.notes || "").toLowerCase().includes(t) ||
      (r.method || []).some(m => m.toLowerCase().includes(t))) return 3;
  return 4;
}

async function renderRecipes() {
  const main = document.getElementById("main");
  const recipes = await getAllRecipes();
  const planIds = await getMealPlan();

  let filtered = recipes.filter(r => {
    const matchesTag = !currentTagFilter || (r.tags || []).includes(currentTagFilter);
    if (!matchesTag) return false;
    return !currentSearch || searchRank(r, currentSearch) < 4;
  });

  if (currentSearch) {
    filtered.sort((a, b) => {
      const ra = searchRank(a, currentSearch), rb = searchRank(b, currentSearch);
      return ra !== rb ? ra - rb : a.title.localeCompare(b.title);
    });
  } else {
    filtered.sort((a, b) => a.title.localeCompare(b.title));
  }

  const tags = allTags(recipes);

  let html = `<div class="toolbar">
    <input type="text" id="searchInput" placeholder="Search recipes, tags, ingredients..." value="${escapeAttr(currentSearch)}">
    <select id="tagSelect">
      <option value="">All tags</option>
      ${tags.map(t => `<option value="${escapeAttr(t)}" ${t === currentTagFilter ? "selected" : ""}>${escapeHtml(t)}</option>`).join("")}
    </select>
    <button class="secondary-btn" id="openAddBtn" title="Add a recipe">+ Add recipe</button>
  </div>`;

  if (recipesFlash) {
    html += `<div class="status-msg status-ok">${escapeHtml(recipesFlash)}</div>`;
    recipesFlash = "";
  }

  if (filtered.length === 0) {
    html += `<div class="empty-msg">No recipes match yet. Tap "+ Add recipe" above, or clear your search.</div>`;
  } else {
    filtered.forEach(r => {
      const inPlan = planIds.includes(r.id);
      const metaParts = [r.servesLabel, r.time].filter(Boolean).join(" &middot; ");
      html += `<div class="recipe-card" data-id="${escapeAttr(r.id)}">
        <h3>${escapeHtml(r.title)}</h3>
        <div class="recipe-meta">${metaParts}</div>
        ${sourceLineHtml(r)}
        <div class="tag-row">${(r.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>
        <div class="card-actions">
          <button class="mini-btn ${inPlan ? "selected" : ""}" data-action="plan-toggle" data-id="${escapeAttr(r.id)}">${inPlan ? "✓ In meal plan" : "+ Add to meal plan"}</button>
          <button class="mini-btn danger" data-action="delete" data-id="${escapeAttr(r.id)}">Delete</button>
        </div>
      </div>`;
    });
  }

  main.innerHTML = html;

  document.getElementById("searchInput").addEventListener("input", (e) => {
    currentSearch = e.target.value;
    renderRecipes();
  });
  document.getElementById("tagSelect").addEventListener("change", (e) => {
    currentTagFilter = e.target.value;
    renderRecipes();
  });
  document.getElementById("openAddBtn").addEventListener("click", () => renderAdd());

  main.querySelectorAll(".recipe-card").forEach(card => {
    card.addEventListener("click", (e) => {
      if (e.target.closest("button") || e.target.closest("a")) return;
      renderDetail(card.dataset.id);
    });
  });
  main.querySelectorAll('[data-action="plan-toggle"]').forEach(btn => {
    btn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const r = recipes.find(x => x.id === btn.dataset.id);
      if (!r) return;
      const planIdsNow = await getMealPlan();
      if (planIdsNow.includes(r.id)) {
        await removeRecipeFromMealPlan(r.id);
        recipesFlash = `Removed "${r.title}" from your meal plan.`;
      } else {
        const result = await addRecipeToMealPlan(r);
        recipesFlash = `Added "${r.title}" to your meal plan (${result.added} new item(s), ${result.merged} merged into existing lines).`;
      }
      renderRecipes();
    });
  });
  main.querySelectorAll('[data-action="delete"]').forEach(btn => {
    btn.addEventListener("click", async (e) => {
      e.stopPropagation();
      if (!confirm("Delete this recipe? This can't be undone (unless you have an exported backup).")) return;
      await deleteRecipe(btn.dataset.id);
      await removeRecipeFromMealPlan(btn.dataset.id);
      renderRecipes();
    });
  });
}

function sourceLineHtml(r) {
  if (!r.source && !r.sourceUrl) return "";
  if (r.sourceUrl) {
    return `<div class="recipe-meta"><a href="${escapeAttr(r.sourceUrl)}" target="_blank" rel="noopener">${escapeHtml(r.source || r.sourceUrl)} ↗</a></div>`;
  }
  return `<div class="recipe-meta">${escapeHtml(r.source)}</div>`;
}

async function renderDetail(id, flash) {
  const main = document.getElementById("main");
  const recipes = await getAllRecipes();
  const r = recipes.find(x => x.id === id);
  if (!r) { renderRecipes(); return; }
  const planIds = await getMealPlan();
  const inPlan = planIds.includes(r.id);

  main.innerHTML = `
    ${flash ? `<div class="status-msg status-ok">${escapeHtml(flash)}</div>` : ""}
    <button class="back-btn" id="backBtn">&larr; Back to recipes</button>
    <div class="detail-card">
      <h2>${escapeHtml(r.title)}</h2>
      <div class="recipe-meta">${[r.servesLabel, r.time].filter(Boolean).map(escapeHtml).join(" &middot; ")}</div>
      ${r.source || r.sourceUrl ? `<div>${r.sourceUrl
        ? `<a class="source-link" href="${escapeAttr(r.sourceUrl)}" target="_blank" rel="noopener">${escapeHtml(r.source || "View source")} ↗</a>`
        : `<div class="recipe-meta">${escapeHtml(r.source)}</div>`}</div>` : ""}
      <div class="tag-row">${(r.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>

      <div class="section-label">Ingredients</div>
      <ul class="ing-list">${(r.ingredients || []).map(i => `<li>${escapeHtml(i)}</li>`).join("")}</ul>

      <div class="section-label">Method</div>
      <ol class="method-list">${(r.method || []).map(m => `<li>${escapeHtml(m)}</li>`).join("")}</ol>

      ${r.notes ? `<div class="section-label">Notes</div><div class="notes-box">${escapeHtml(r.notes)}</div>` : ""}

      <div class="card-actions">
        <button class="mini-btn ${inPlan ? "selected" : ""}" id="planToggleBtn">${inPlan ? "✓ In meal plan" : "+ Add to meal plan"}</button>
        <button class="mini-btn" id="editBtn">Edit recipe</button>
      </div>
    </div>
  `;
  document.getElementById("backBtn").addEventListener("click", renderRecipes);
  document.getElementById("planToggleBtn").addEventListener("click", async () => {
    if (inPlan) {
      await removeRecipeFromMealPlan(r.id);
      renderDetail(r.id, `Removed "${r.title}" from your meal plan.`);
    } else {
      const result = await addRecipeToMealPlan(r);
      renderDetail(r.id, `Added to your meal plan (${result.added} new item(s), ${result.merged} merged into existing lines).`);
    }
  });
  document.getElementById("editBtn").addEventListener("click", () => renderRecipeForm(r));
}

/* ---------- Meal plan ---------- */

async function addRecipeToMealPlan(recipe) {
  const plan = await getMealPlan();
  if (!plan.includes(recipe.id)) {
    plan.push(recipe.id);
    await saveMealPlan(plan);
  }
  const catalog = await getIngredientCatalog();
  const items = await getShopItems();
  let added = 0, merged = 0;

  (recipe.ingredients || []).forEach(raw => {
    const parsed = parseIngredient(raw);
    const catalogEntry = matchCatalog(parsed.name, catalog);
    const displayName = catalogEntry ? catalogEntry.name : parsed.name;
    const mergeKey = buildMergeKey(catalogEntry, parsed.name);
    const category = catalogEntry ? catalogEntry.category : "Other";
    const staple = catalogEntry ? !!catalogEntry.staple : false;

    const existing = items.find(i => !i.manual && i.mergeKey === mergeKey && i.unit === parsed.unit);
    if (existing) {
      if (parsed.amount != null) existing.amount = (existing.amount || 0) + parsed.amount;
      if (parsed.parenAmount != null) existing.parenAmount = (existing.parenAmount || 0) + parsed.parenAmount;
      if (!existing.meals.includes(recipe.title)) existing.meals.push(recipe.title);
      existing.name = displayName;
      existing.text = formatItemText(existing);
      merged++;
    } else {
      const item = {
        id: genId(), mergeKey, name: displayName,
        amount: parsed.amount, unit: parsed.unit,
        parenAmount: parsed.parenAmount, parenUnit: parsed.parenUnit,
        text: "", meals: [recipe.title], manual: false, checked: false,
        category, staple
      };
      item.text = formatItemText(item);
      items.push(item);
      added++;
    }
  });

  await saveShopItems(items);
  return { added, merged };
}

async function removeRecipeFromMealPlan(recipeId) {
  const plan = await getMealPlan();
  await saveMealPlan(plan.filter(id => id !== recipeId));
}

async function renderMealPlan() {
  const main = document.getElementById("main");
  const planIds = await getMealPlan();
  const recipes = await getAllRecipes();
  const planned = planIds.map(id => recipes.find(r => r.id === id)).filter(Boolean);
  planned.sort((a, b) => a.title.localeCompare(b.title));

  let html = `<p class="intro-note">Recipes you're cooking this period. Adding one here merges its ingredients into your Shopping List, tagged with which meal they're for.</p>`;

  if (planned.length === 0) {
    html += `<div class="empty-msg">No meals planned yet. Head to Recipes and tap "+ Add to meal plan" on what you're cooking.</div>`;
  } else {
    planned.forEach(r => {
      const metaParts = [r.servesLabel, r.time].filter(Boolean).join(" &middot; ");
      html += `<div class="recipe-card" data-id="${escapeAttr(r.id)}">
        <h3>${escapeHtml(r.title)}</h3>
        <div class="recipe-meta">${metaParts}</div>
        <div class="tag-row">${(r.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join("")}</div>
        <div class="card-actions">
          <button class="mini-btn danger" data-action="remove-plan" data-id="${escapeAttr(r.id)}">Remove from plan</button>
        </div>
      </div>`;
    });
    html += `<div class="btn-row" style="margin-top:6px;"><button class="secondary-btn" id="goShopBtn">Go to Shopping List</button></div>`;
  }

  main.innerHTML = html;
  main.querySelectorAll(".recipe-card").forEach(card => {
    card.addEventListener("click", (e) => {
      if (e.target.closest("button")) return;
      renderDetail(card.dataset.id);
    });
  });
  main.querySelectorAll('[data-action="remove-plan"]').forEach(btn => {
    btn.addEventListener("click", async (e) => {
      e.stopPropagation();
      await removeRecipeFromMealPlan(btn.dataset.id);
      renderMealPlan();
    });
  });
  const goShopBtn = document.getElementById("goShopBtn");
  if (goShopBtn) goShopBtn.addEventListener("click", () => setTab("shop"));
}

/* ---------- Shopping list ---------- */

async function addManualItem() {
  const input = document.getElementById("newItemInput");
  const text = input.value.trim();
  if (!text) return;
  const catalog = await getIngredientCatalog();
  const catalogEntry = matchCatalog(text, catalog);
  const items = await getShopItems();
  items.push({
    id: genId(), mergeKey: "manual:" + genId(), name: text, amount: null, unit: null,
    parenAmount: null, parenUnit: null, text,
    meals: [], manual: true, checked: false,
    category: catalogEntry ? catalogEntry.category : "Other",
    staple: catalogEntry ? !!catalogEntry.staple : false
  });
  await saveShopItems(items);
  renderShoppingList();
}

function buildShoppingListText(items) {
  const unchecked = items.filter(i => !i.checked);
  const nonStaple = unchecked.filter(i => !i.staple);
  const staples = unchecked.filter(i => i.staple);
  const lines = ["Shopping List", ""];

  CATEGORY_ORDER.forEach(cat => {
    const group = nonStaple.filter(i => i.category === cat).sort((a, b) => a.name.localeCompare(b.name));
    if (group.length === 0) return;
    lines.push(cat + ":");
    group.forEach(i => lines.push("- " + i.text));
    lines.push("");
  });

  if (staples.length > 0) {
    lines.push("Staples (probably already have):");
    staples.sort((a, b) => a.name.localeCompare(b.name)).forEach(i => lines.push("- " + i.text));
    lines.push("");
  }

  return lines.join("\n").trim();
}

async function copyShoppingListText() {
  const items = await getShopItems();
  const text = buildShoppingListText(items);
  try {
    await navigator.clipboard.writeText(text);
    shopFlash = { message: "Copied! Paste it into your notes app.", undo: null };
  } catch (e) {
    shopFlash = { message: "Couldn't copy automatically -- try again, or select and copy manually.", undo: null };
  }
  renderShoppingList();
}

async function renderShoppingList() {
  const main = document.getElementById("main");
  const items = await getShopItems();
  const unchecked = items.filter(i => !i.checked);
  const checked = items.filter(i => i.checked);
  const nonStaple = unchecked.filter(i => !i.staple);
  const staples = unchecked.filter(i => i.staple);

  let html = `<div class="add-item-row">
    <input type="text" id="newItemInput" placeholder="Add an item...">
    <button class="primary-btn" id="addItemBtn" style="margin-top:0;">Add</button>
  </div>`;

  if (shopFlash) {
    html += `<div class="status-msg status-ok with-action">
      <span>${escapeHtml(shopFlash.message)}</span>
      ${shopFlash.undo ? `<button class="link-btn" id="undoBtn">Undo</button>` : ""}
    </div>`;
  }

  if (items.length === 0) {
    html += `<div class="empty-msg">Your shopping list is empty. Add items above, or head to the Meal Plan tab and add a recipe.</div>`;
  } else {
    if (nonStaple.length === 0 && staples.length === 0) {
      html += `<div class="empty-msg">Everything's checked off!${checked.length ? " Tap “Show checked” below to review." : ""}</div>`;
    }
    CATEGORY_ORDER.forEach(cat => {
      const group = nonStaple.filter(i => i.category === cat).sort((a, b) => a.name.localeCompare(b.name));
      if (group.length === 0) return;
      html += `<div class="section-label">${escapeHtml(cat)}</div><div>${group.map(i => renderShopItem(i)).join("")}</div>`;
    });
    if (staples.length > 0) {
      html += `<div class="staple-section">
        <div class="section-label">Staples (probably already in the cupboard)</div>
        <div class="staple-hint">Flagged just in case -- check your stock before buying.</div>
        <div>${staples.sort((a, b) => a.name.localeCompare(b.name)).map(i => renderShopItem(i, { hideBadge: true })).join("")}</div>
      </div>`;
    }

    html += `<div class="btn-row" style="margin-top:16px;">`;
    html += `<button class="secondary-btn" id="copyTextBtn">Copy as text</button>`;
    if (checked.length > 0) {
      html += `<button class="secondary-btn" id="toggleCheckedBtn">${showCheckedItems ? "Hide" : "Show"} checked (${checked.length})</button>`;
    }
    html += `<button class="secondary-btn" id="clearCheckedBtn">Clear checked items</button><button class="secondary-btn" id="clearAllBtn">Clear whole list</button></div>`;

    if (showCheckedItems && checked.length > 0) {
      html += `<div class="section-label">Checked off</div><div>${checked.sort((a, b) => a.name.localeCompare(b.name)).map(i => renderShopItem(i)).join("")}</div>`;
    }
  }

  main.innerHTML = html;

  document.getElementById("addItemBtn").addEventListener("click", addManualItem);
  document.getElementById("newItemInput").addEventListener("keydown", (e) => {
    if (e.key === "Enter") addManualItem();
  });

  const undoBtn = document.getElementById("undoBtn");
  if (undoBtn) undoBtn.addEventListener("click", async () => {
    if (shopFlash && shopFlash.undo) await shopFlash.undo();
    shopFlash = null;
    renderShoppingList();
  });

  main.querySelectorAll(".shop-item").forEach(el => {
    const id = el.dataset.id;
    el.querySelector(".box").addEventListener("click", async (e) => {
      e.stopPropagation();
      const all = await getShopItems();
      const item = all.find(i => i.id === id);
      if (!item) return;
      item.checked = !item.checked;
      await saveShopItems(all);
      if (item.checked) {
        shopFlash = {
          message: `Checked off "${item.name}".`,
          undo: async () => {
            const all2 = await getShopItems();
            const it2 = all2.find(i => i.id === id);
            if (it2) it2.checked = false;
            await saveShopItems(all2);
          }
        };
      } else {
        shopFlash = null;
      }
      renderShoppingList();
    });
    const textEl = el.querySelector(".item-text");
    if (textEl) {
      textEl.addEventListener("click", (e) => {
        e.stopPropagation();
        startEditItem(el, id);
      });
    }
    const delBtn = el.querySelector('[data-action="delete-item"]');
    if (delBtn) {
      delBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        const all = await getShopItems();
        await saveShopItems(all.filter(i => i.id !== id));
        renderShoppingList();
      });
    }
  });

  const copyTextBtn = document.getElementById("copyTextBtn");
  if (copyTextBtn) copyTextBtn.addEventListener("click", copyShoppingListText);
  const toggleCheckedBtn = document.getElementById("toggleCheckedBtn");
  if (toggleCheckedBtn) toggleCheckedBtn.addEventListener("click", () => {
    showCheckedItems = !showCheckedItems;
    renderShoppingList();
  });
  const clearCheckedBtn = document.getElementById("clearCheckedBtn");
  if (clearCheckedBtn) clearCheckedBtn.addEventListener("click", async () => {
    const all = await getShopItems();
    const removed = all.filter(i => i.checked);
    if (removed.length === 0) return;
    await saveShopItems(all.filter(i => !i.checked));
    shopFlash = {
      message: `Cleared ${removed.length} checked item(s).`,
      undo: async () => {
        const cur = await getShopItems();
        await saveShopItems(cur.concat(removed));
      }
    };
    renderShoppingList();
  });
  const clearAllBtn = document.getElementById("clearAllBtn");
  if (clearAllBtn) clearAllBtn.addEventListener("click", async () => {
    const all = await getShopItems();
    if (all.length === 0) return;
    if (!confirm("Clear the entire shopping list?")) return;
    await saveShopItems([]);
    shopFlash = {
      message: `Cleared the whole list (${all.length} item(s)).`,
      undo: async () => { await saveShopItems(all); }
    };
    renderShoppingList();
  });
}

function renderShopItem(item, opts) {
  opts = opts || {};
  const mealsLabel = (item.meals && item.meals.length) ? item.meals.join(", ") : "";
  return `<div class="shop-item ${item.checked ? "checked" : ""}" data-id="${escapeAttr(item.id)}">
    <div class="box"><svg viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg></div>
    <div class="item-body">
      <div class="item-text">${escapeHtml(item.text)}</div>
      ${mealsLabel ? `<div class="item-src">${escapeHtml(mealsLabel)}</div>` : ""}
    </div>
    <div class="item-controls">
      ${item.staple && !opts.hideBadge ? `<span class="icon-btn on" style="pointer-events:none;">Staple</span>` : ""}
      <button class="icon-btn" data-action="delete-item" title="Remove item">✕</button>
    </div>
  </div>`;
}

function startEditItem(el, id) {
  const bodyEl = el.querySelector(".item-body");
  const current = el.querySelector(".item-text").textContent;
  bodyEl.innerHTML = `<input type="text" class="item-text-input" value="${escapeAttr(current)}">`;
  const input = bodyEl.querySelector("input");
  input.focus();
  input.setSelectionRange(current.length, current.length);
  const save = async () => {
    const val = input.value.trim();
    const all = await getShopItems();
    const item = all.find(i => i.id === id);
    if (item && val) { item.text = val; item.manual = true; }
    await saveShopItems(all);
    renderShoppingList();
  };
  input.addEventListener("blur", save);
  input.addEventListener("keydown", (e) => { if (e.key === "Enter") input.blur(); });
  input.addEventListener("click", (e) => e.stopPropagation());
}

/* ---------- Add / edit a recipe ---------- */

const SCHEMA_EXAMPLE = {
  id: "short-unique-slug",
  title: "Recipe Title",
  source: "e.g. cookbook name & page, or website name",
  sourceUrl: "https://example.com/recipe (optional, if it's online)",
  tags: ["chicken", "quick", "weeknight"],
  serves: 2,
  time: "20 min",
  ingredients: ["200g chicken breast", "1 lemon"],
  method: ["Step one.", "Step two."],
  notes: "Optional tips or variations.",
  dateAdded: "2026-07-11"
};

function detectDefaultServes(item) {
  if (item.serves && !isNaN(item.serves)) return Number(item.serves);
  const label = item.servesLabel || "";
  const m = label.match(/(\d+)/);
  if (m) return Number(m[1]);
  return null;
}

function buildClaudePrompt() {
  return `Please read the recipe in the link or photo I'm about to share, and return it as a single JSON object (or a JSON array if there's more than one recipe) using exactly this schema -- no extra commentary, just the JSON:

${JSON.stringify(SCHEMA_EXAMPLE, null, 2)}

Notes:
- ingredients and method should each be an array of strings, one item/step per entry.
- serves should be a plain number if you can tell how many it serves.
- sourceUrl is optional -- include it only if the recipe came from a link.
- Only title and ingredients are strictly required; leave other fields blank/empty if unknown.`;
}

async function copyClaudePrompt() {
  const statusEl = document.getElementById("copyStatus");
  try {
    await navigator.clipboard.writeText(buildClaudePrompt());
    statusEl.innerHTML = `<div class="status-msg status-ok">Copied! Paste it into a Claude chat along with your recipe link or photo.</div>`;
  } catch (e) {
    statusEl.innerHTML = `<div class="status-msg status-err">Couldn't copy automatically -- select and copy the schema below instead.</div>`;
  }
}

function renderAdd(statusMsg) {
  const main = document.getElementById("main");
  main.innerHTML = `
    <button class="back-btn" id="addBackBtn">&larr; Back to recipes</button>
    <div class="settings-card">
      <h3>Add a recipe manually</h3>
      <p>Type it in yourself -- good for quick edits or recipes you already know by heart.</p>
      <div class="btn-row"><button class="primary-btn" id="manualAddBtn" style="margin-top:0;">Add manually</button></div>
    </div>
    <div class="settings-card">
      <h3>Add via Claude (paste JSON)</h3>
      <p>Copy the prompt below into a normal Claude chat along with a link or photo of the recipe, then paste back whatever JSON it returns.</p>
      <div class="btn-row"><button class="secondary-btn" id="copyPromptBtn">Copy prompt for Claude</button></div>
      <div id="copyStatus"></div>
      <textarea id="jsonInput" placeholder="Paste recipe JSON here..." style="margin-top:12px;"></textarea>
      <button class="primary-btn" id="reviewJsonBtn">Review before adding</button>
      ${statusMsg ? statusMsg : ""}
    </div>
    <div class="schema-box">
      <strong>Schema (included in the copied prompt):</strong>
      <pre>${escapeHtml(JSON.stringify(SCHEMA_EXAMPLE, null, 2))}</pre>
      <div>Only <code>title</code> and <code>ingredients</code> are required — everything else is optional. If <code>id</code> is missing, one is generated from the title.</div>
    </div>
  `;
  document.getElementById("addBackBtn").addEventListener("click", renderRecipes);
  document.getElementById("manualAddBtn").addEventListener("click", () => renderRecipeForm(null));
  document.getElementById("copyPromptBtn").addEventListener("click", copyClaudePrompt);
  document.getElementById("reviewJsonBtn").addEventListener("click", handleJsonReview);
}

function renderRecipeForm(recipe) {
  const main = document.getElementById("main");
  const isEdit = !!recipe;
  const r = recipe || { title: "", source: "", sourceUrl: "", tags: [], serves: null, servesLabel: "", time: "", ingredients: [], method: [], notes: "" };
  const defaultServes = r.serves || detectDefaultServes(r) || 4;

  main.innerHTML = `
    <button class="back-btn" id="formBackBtn">&larr; ${isEdit ? "Back to recipe" : "Back"}</button>
    <div class="detail-card">
      <h2>${isEdit ? "Edit recipe" : "Add a recipe"}</h2>
      <div class="form-field"><label>Title</label><input type="text" id="fTitle" value="${escapeAttr(r.title)}"></div>
      <div class="form-row-2">
        <div class="form-field"><label>Source (book & page, or website name)</label><input type="text" id="fSource" value="${escapeAttr(r.source || "")}"></div>
        <div class="form-field"><label>Source link (optional)</label><input type="url" id="fSourceUrl" value="${escapeAttr(r.sourceUrl || "")}"></div>
      </div>
      <div class="form-row-2">
        <div class="form-field"><label>Serves</label><input type="number" min="1" id="fServes" value="${defaultServes}"></div>
        <div class="form-field"><label>Time</label><input type="text" id="fTime" value="${escapeAttr(r.time || "")}" placeholder="e.g. 20 min"></div>
      </div>
      <div class="form-field"><label>Tags (comma separated)</label><input type="text" id="fTags" value="${escapeAttr((r.tags || []).join(", "))}"></div>
      <div class="form-field"><label>Ingredients (one per line)</label><textarea id="fIngredients">${escapeHtml((r.ingredients || []).join("\n"))}</textarea></div>
      <div class="form-field"><label>Method (one step per line)</label><textarea id="fMethod">${escapeHtml((r.method || []).join("\n"))}</textarea></div>
      <div class="form-field"><label>Notes</label><textarea id="fNotes" style="min-height:70px;">${escapeHtml(r.notes || "")}</textarea></div>
      <button class="primary-btn" id="saveRecipeBtn">${isEdit ? "Save changes" : "Save recipe"}</button>
      <div id="formStatus"></div>
    </div>
  `;
  document.getElementById("formBackBtn").addEventListener("click", () => {
    if (isEdit) renderDetail(r.id); else renderAdd();
  });
  document.getElementById("saveRecipeBtn").addEventListener("click", async () => {
    const title = document.getElementById("fTitle").value.trim();
    const ingredients = document.getElementById("fIngredients").value.split("\n").map(s => s.trim()).filter(Boolean);
    if (!title || ingredients.length === 0) {
      document.getElementById("formStatus").innerHTML = `<div class="status-msg status-err">Title and at least one ingredient are required.</div>`;
      return;
    }
    const serves = Number(document.getElementById("fServes").value) || null;
    const method = document.getElementById("fMethod").value.split("\n").map(s => s.trim()).filter(Boolean);
    const tags = document.getElementById("fTags").value.split(",").map(s => s.trim()).filter(Boolean);
    const source = document.getElementById("fSource").value.trim();
    const sourceUrl = document.getElementById("fSourceUrl").value.trim();
    const time = document.getElementById("fTime").value.trim();
    const notes = document.getElementById("fNotes").value.trim();
    let servesLabel = r.servesLabel || "";
    if (serves) servesLabel = /makes/i.test(servesLabel) ? `Makes ${serves} portions` : `Serves ${serves}`;

    const savedRecipe = {
      id: isEdit ? r.id : slugify(title) + "-" + Date.now().toString(36).slice(-4),
      title, source, sourceUrl, tags, serves, servesLabel, time, ingredients, method, notes,
      dateAdded: r.dateAdded || new Date().toISOString().slice(0, 10)
    };
    await putRecipe(savedRecipe);
    renderDetail(savedRecipe.id, isEdit ? "Recipe updated." : "Recipe added.");
  });
}

function handleJsonReview() {
  const raw = document.getElementById("jsonInput").value.trim();
  if (!raw) return;
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    renderAdd(`<div class="status-msg status-err">Couldn't parse that as JSON: ${escapeHtml(e.message)}</div>`);
    return;
  }
  const items = Array.isArray(parsed) ? parsed : [parsed];
  const valid = items.filter(item => item.title && item.ingredients);
  const skipped = items.length - valid.length;
  if (valid.length === 0) {
    renderAdd(`<div class="status-msg status-err">Nothing to add — every item needs at least a title and ingredients.</div>`);
    return;
  }
  pendingImport = valid.map(item => ({ item, serves: detectDefaultServes(item) }));
  renderReview(skipped);
}

function renderReview(skippedCount) {
  const main = document.getElementById("main");
  let html = `<div class="settings-card">
    <h3>Confirm servings</h3>
    <p>Check how many each recipe serves before adding it — adjust any that aren't right.</p>`;
  pendingImport.forEach((entry, idx) => {
    html += `<div class="serves-review">
      <h4>${escapeHtml(entry.item.title)}</h4>
      <div class="serves-row">
        <label for="serves-${idx}">Serves</label>
        <input type="number" min="1" id="serves-${idx}" value="${entry.serves != null ? entry.serves : ""}" placeholder="?">
      </div>
    </div>`;
  });
  html += `<div class="btn-row" style="margin-top:6px;">
      <button class="primary-btn" id="confirmImportBtn" style="margin-top:0;">Add ${pendingImport.length} recipe(s)</button>
      <button class="secondary-btn" id="cancelImportBtn">Cancel</button>
    </div>
    ${skippedCount ? `<div class="status-msg status-err" style="margin-top:10px;">Skipped ${skippedCount} item(s) missing a title or ingredients.</div>` : ""}
  </div>`;
  main.innerHTML = html;

  document.getElementById("confirmImportBtn").addEventListener("click", handleConfirmImport);
  document.getElementById("cancelImportBtn").addEventListener("click", () => {
    pendingImport = null;
    renderAdd();
  });
}

async function handleConfirmImport() {
  let added = 0;
  for (let idx = 0; idx < pendingImport.length; idx++) {
    const { item } = pendingImport[idx];
    const servesInput = document.getElementById(`serves-${idx}`).value;
    const serves = servesInput ? Number(servesInput) : null;
    let servesLabel = item.servesLabel || "";
    if (serves) {
      servesLabel = /makes/i.test(servesLabel) ? `Makes ${serves} portions` : `Serves ${serves}`;
    }
    const recipe = {
      id: item.id ? slugify(item.id) : slugify(item.title) + "-" + Date.now().toString(36).slice(-4),
      title: item.title,
      source: item.source || "",
      sourceUrl: item.sourceUrl || "",
      tags: item.tags || [],
      serves: serves || null,
      servesLabel,
      time: item.time || "",
      ingredients: item.ingredients || [],
      method: item.method || [],
      notes: item.notes || "",
      dateAdded: item.dateAdded || new Date().toISOString().slice(0, 10)
    };
    await putRecipe(recipe);
    added++;
  }
  pendingImport = null;
  renderAdd(`<div class="status-msg status-ok">Added ${added} recipe(s).</div>`);
}

/* ---------- Settings: export / import, ingredient catalog ---------- */

function renderIngredientCatalogSection(catalog) {
  const rows = catalog.slice().sort((a, b) => a.name.localeCompare(b.name)).map(entry => `
    <div class="ingredient-row" data-id="${escapeAttr(entry.id)}">
      <input type="text" class="ing-name" value="${escapeAttr(entry.name)}">
      <select class="ing-category">
        ${CATEGORY_ORDER.map(c => `<option value="${escapeAttr(c)}" ${c === entry.category ? "selected" : ""}>${escapeHtml(c)}</option>`).join("")}
      </select>
      <label class="staple-check"><input type="checkbox" class="ing-staple" ${entry.staple ? "checked" : ""}> Staple</label>
      <input type="text" class="ing-aliases" value="${escapeAttr((entry.aliases || []).join(", "))}" placeholder="aliases, comma separated">
      <button class="icon-btn" data-action="delete-ing">✕</button>
    </div>`).join("");

  return `<div class="settings-card">
    <h3>Ingredient list</h3>
    <p>Canonical ingredients recipes get matched against -- so "rice sachet" and "packet of basmati rice" can become one shopping-list line, and mark anything as a staple you usually already have.</p>
    <div id="ingRows">${rows || `<div class="empty-msg">No ingredients yet -- add one below.</div>`}</div>
    <div class="ingredient-row" style="border-top:2px solid var(--line); margin-top:10px; padding-top:12px;">
      <input type="text" id="newIngName" placeholder="Name (e.g. Basmati rice)">
      <select id="newIngCategory">
        ${CATEGORY_ORDER.map(c => `<option value="${escapeAttr(c)}">${escapeHtml(c)}</option>`).join("")}
      </select>
      <label class="staple-check"><input type="checkbox" id="newIngStaple"> Staple</label>
      <input type="text" id="newIngAliases" placeholder="aliases, comma separated">
      <button class="secondary-btn" id="addIngBtn">Add</button>
    </div>
  </div>`;
}

function wireIngredientCatalogEvents() {
  const main = document.getElementById("main");
  main.querySelectorAll(".ingredient-row[data-id]").forEach(row => {
    const id = row.dataset.id;
    const save = async () => {
      const catalog = await getIngredientCatalog();
      const entry = catalog.find(e => e.id === id);
      if (!entry) return;
      entry.name = row.querySelector(".ing-name").value.trim() || entry.name;
      entry.category = row.querySelector(".ing-category").value;
      entry.staple = row.querySelector(".ing-staple").checked;
      entry.aliases = row.querySelector(".ing-aliases").value.split(",").map(s => s.trim()).filter(Boolean);
      await saveIngredientCatalog(catalog);
    };
    row.querySelector(".ing-name").addEventListener("blur", save);
    row.querySelector(".ing-aliases").addEventListener("blur", save);
    row.querySelector(".ing-category").addEventListener("change", save);
    row.querySelector(".ing-staple").addEventListener("change", save);
    row.querySelector('[data-action="delete-ing"]').addEventListener("click", async () => {
      const catalog = await getIngredientCatalog();
      await saveIngredientCatalog(catalog.filter(e => e.id !== id));
      renderSettings();
    });
  });
  const addIngBtn = document.getElementById("addIngBtn");
  if (addIngBtn) addIngBtn.addEventListener("click", async () => {
    const name = document.getElementById("newIngName").value.trim();
    if (!name) return;
    const category = document.getElementById("newIngCategory").value;
    const staple = document.getElementById("newIngStaple").checked;
    const aliases = document.getElementById("newIngAliases").value.split(",").map(s => s.trim()).filter(Boolean);
    if (aliases.length === 0) aliases.push(name.toLowerCase());
    const catalog = await getIngredientCatalog();
    catalog.push({ id: slugify(name) + "-" + Date.now().toString(36).slice(-4), name, category, staple, aliases });
    await saveIngredientCatalog(catalog);
    renderSettings();
  });
}

async function renderSettings() {
  const main = document.getElementById("main");
  const catalog = await getIngredientCatalog();
  main.innerHTML = `
    <div class="settings-card">
      <h3>Export your library</h3>
      <p>Download everything in your Rustle Up library as a single JSON file — useful for backups, or to share your library with your partner.</p>
      <div class="btn-row"><button class="secondary-btn" id="exportBtn">Export as JSON</button></div>
    </div>
    <div class="settings-card">
      <h3>Import a library</h3>
      <p>Import a previously exported JSON file. Recipes are matched by id — importing will update recipes that already exist and add any new ones, without duplicating.</p>
      <div class="btn-row">
        <button class="secondary-btn" id="importBtn">Choose file to import</button>
        <input type="file" id="fileInput" accept="application/json">
      </div>
      <div id="importStatus"></div>
    </div>
    ${renderIngredientCatalogSection(catalog)}
    <div class="settings-card">
      <h3>About this app</h3>
      <p>Everything here lives in this browser's IndexedDB — nothing is sent anywhere, and there's no account or server involved. Clearing your browser data will clear your recipes too, so export regularly if you want a backup.</p>
    </div>
  `;
  document.getElementById("exportBtn").addEventListener("click", exportLibrary);
  document.getElementById("importBtn").addEventListener("click", () => document.getElementById("fileInput").click());
  document.getElementById("fileInput").addEventListener("change", handleFileImport);
  wireIngredientCatalogEvents();
}

async function exportLibrary() {
  const recipes = await getAllRecipes();
  const mealPlan = await getMealPlan();
  const shopItems = await getShopItems();
  const ingredientCatalog = await getIngredientCatalog();
  const payload = { recipes, mealPlan, shopItems, ingredientCatalog };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `rustle-up-export-${new Date().toISOString().slice(0, 10)}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function handleFileImport(e) {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = async (ev) => {
    try {
      const parsed = JSON.parse(ev.target.result);
      const isBundle = !Array.isArray(parsed);
      const recipeItems = isBundle ? (parsed.recipes || []) : parsed;
      let count = 0;
      for (const item of recipeItems) {
        if (!item.title || !item.ingredients) continue;
        const recipe = {
          id: item.id || slugify(item.title) + "-" + Date.now().toString(36).slice(-4),
          title: item.title,
          source: item.source || "",
          sourceUrl: item.sourceUrl || "",
          tags: item.tags || [],
          serves: item.serves || null,
          servesLabel: item.servesLabel || "",
          time: item.time || "",
          ingredients: item.ingredients || [],
          method: item.method || [],
          notes: item.notes || "",
          dateAdded: item.dateAdded || new Date().toISOString().slice(0, 10)
        };
        await putRecipe(recipe);
        count++;
      }
      if (isBundle) {
        if (parsed.mealPlan) await saveMealPlan(parsed.mealPlan);
        if (parsed.shopItems) await saveShopItems(parsed.shopItems);
        if (parsed.ingredientCatalog) await saveIngredientCatalog(parsed.ingredientCatalog);
      }
      document.getElementById("importStatus").innerHTML =
        `<div class="status-msg status-ok">Imported ${count} recipe(s)${isBundle ? ", plus your meal plan, shopping list and ingredient catalog" : ""}.</div>`;
    } catch (err) {
      document.getElementById("importStatus").innerHTML = `<div class="status-msg status-err">Import failed: ${escapeHtml(err.message)}</div>`;
    }
  };
  reader.readAsText(file);
}

/* ---------- Utilities ---------- */

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}
function escapeAttr(str) { return escapeHtml(str); }

/* ---------- Tabs ---------- */

function setTab(tab) {
  currentTab = tab;
  document.getElementById("tabRecipesBtn").classList.toggle("active", tab === "recipes");
  document.getElementById("tabPlanBtn").classList.toggle("active", tab === "mealplan");
  document.getElementById("tabShopBtn").classList.toggle("active", tab === "shop");
  document.getElementById("tabSettingsBtn").classList.toggle("active", tab === "settings");
  if (tab === "recipes") renderRecipes();
  else if (tab === "mealplan") renderMealPlan();
  else if (tab === "shop") { showCheckedItems = false; shopFlash = null; renderShoppingList(); }
  else if (tab === "settings") renderSettings();
}

document.getElementById("tabRecipesBtn").addEventListener("click", () => setTab("recipes"));
document.getElementById("tabPlanBtn").addEventListener("click", () => setTab("mealplan"));
document.getElementById("tabShopBtn").addEventListener("click", () => setTab("shop"));
document.getElementById("tabSettingsBtn").addEventListener("click", () => setTab("settings"));

(async () => {
  db = await openDB();
  await seedIfEmpty();
  await seedCatalogIfEmpty();
  setTab("recipes");
})();

if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("sw.js").catch((err) => {
      console.error("Service worker registration failed:", err);
    });
  });
}
